sudo: required
services:
  - docker

before_install:
  - docker build -f Dockerfile.dev -t andrewmanullang/docker-react .

script:
  - docker run CI=true andrewmanullang/docker-react npm run test -- --coverage
